application: quizz
version: 1
runtime: python
api_version: 1

handlers:
- url: /.*
  script: python/load_dispatcher.py

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (README)|
 )$
