application: quizz
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: gwt/www/com.googlecode.pyquizz.PyQuizz/PyQuizz.html
  upload: gwt/www/com.googlecode.pyquizz.PyQuizz/

- url: /py/.*
  script: python/load_dispatcher.py

- url: /(.*)
  static_files: gwt/www/com.googlecode.pyquizz.PyQuizz/\1
  upload: gwt/www/com.googlecode.pyquizz.PyQuizz/

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (README)|
 (gwt/bin)|
 (gwt/PyQuizz.*)|
 (gwt/src)|
 (gwt/test)|
 (gwt/tomcat)|
 )$
